<a href="https://colab.research.google.com/github/MinsooKwak/RAG/blob/main/test/preprocessing/arvix_cat_extract_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Library**

In [1]:
!pip install -qU langchain-community arxiv pymupdf pdf2image pypdf PyPDF2

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 18.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.0/20.0 MB 25.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 14.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.3/81.3 kB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 kB 3.0 MB/s eta 0:00:00
  Building wheel for sgmllib3k (setup.py) ... done

**카테고리별로 가져올 수 있는지 확인 (가능)**

- 카테고리 정보 : https://arxiv.org/category_taxonomy
- 검색어 search (web) : https://arxiv.org/search/

- 대분류 / 소분류별 가져오기 (따로 구성)
  - 우선 대분류 진행
  - 추후 고도화시 소분류 반영 (이는 어떤 카테고리에서 분석이 부족한지 반영할 수 있음)

In [ ]:
#major_categories = ["cs", "math", "physics", "eess", "econ", "q-bio", "q-fin", "stat", "astro-ph"] # 아래 수정

In [ ]:
import os
import pandas as pd
from langchain.document_loaders import ArxivLoader
from langchain.document_loaders import PyPDFLoader
from pdf2image import convert_from_path
from huggingface_hub import hf_hub_download
#import cv2
#from doclayout_yolo import YOLOv10
from PIL import Image

# ArxivLoader를 활용해 논문을 가져옵니다
loader = ArxivLoader(
    query= "cat : q-bio.*",               # 카테고리별 추출 가능 여부 Test  #f"cat:{category}"
    load_max_docs=50,               # 최대 문서 수
    load_all_available_meta=True    # 메타데이터 전체 로드 여부
)
docs = loader.load()

print(f"Loaded documents: {len(docs)}")


# 메타데이터 정보를 데이터프레임으로 저장
metadata_list = []
for doc in docs:
    metadata = doc.metadata
    metadata_list.append({
        'Title': metadata.get('Title', ''),
        'Summary': metadata.get('Summary', ''),
        'PDF Link': metadata.get('links', [])[-1] if metadata.get('links') else ''
    })

dataframe = pd.DataFrame(metadata_list)

# 데이터프레임 확인
print(dataframe)

Loaded documents: 3
                                   Title  \
0      Semistability and CAT(0) Geometry
1                  Quantum Mona Lisa Cat
2  On the Topological Complexity of Maps

                                             Summary  \
0  We explain why semistability of a one-ended pr...
1  Schr\"{o}dinger's Cat was proposed by Erwin Sc...
2  We define and develop a homotopy invariant not...

                            PDF Link
0  http://arxiv.org/pdf/1703.07003v1
1  http://arxiv.org/pdf/2001.10184v2
2  http://arxiv.org/pdf/2011.10646v1

In [ ]:
dataframe.head()

,Title,Summary,PDF Link
0,Semistability and CAT(0) Geometry,We explain why semistability of a one-ended pr...,http://arxiv.org/pdf/1703.07003v1
1,Quantum Mona Lisa Cat,"Schr\""{o}dinger's Cat was proposed by Erwin Sc...",http://arxiv.org/pdf/2001.10184v2
2,On the Topological Complexity of Maps,We define and develop a homotopy invariant not...,http://arxiv.org/pdf/2011.10646v1

In [ ]:
test_queries_lst = ["cat : cs.*", "cat : math.*", "cat : physics.*", "cat : eess.*", "cat : econ.*", "cat : q-bio.*", "cat : q-fin*", "cat : stat*", "cat : astro-ph.*"]
len(test_queries_lst)

9

In [ ]:
# 전체 카테고리(대분류) 추출 코드 (arxivloader편) - 미사용
import os
import pandas as pd
from langchain.document_loaders import ArxivLoader

# 쿼리 리스트 및 각 쿼리에 따른 최대 문서 수 설정
queries = ["cat : cs.*", "cat : math.*", "cat : physics.*", "cat : eess.*", "cat : econ.*", "cat : q-bio.*", "cat : q-fin*", "cat : stat*", "cat : astro-ph.*"]
load_max_docs_list = [5, 5, 5, 5, 5, 5, 5, 5, 5]  # 9개의 category이므로 우선 5개씩 저장해서 활용

# 결과를 저장할 리스트 초기화
metadata_list = []

# 각 쿼리에 대해 문서 로드 및 처리
for query, max_docs in zip(queries, load_max_docs_list):
    # ArxivLoader를 통해 문서 로드
    loader = ArxivLoader(
        query=query,                  # 현재 쿼리
        load_max_docs=max_docs,       # 최대 문서 수
        load_all_available_meta=True  # 메타데이터 전체 로드
    )
    docs = loader.load()

    # 각 문서에 대해 메타데이터 추출 및 저장
    for doc in docs:
        metadata = doc.metadata
        metadata_list.append({
            'Query': query,  # 쿼리 정보 추가
            'Title': metadata.get('Title', ''),
            'Summary': metadata.get('Summary', ''),
            'PDF Link': metadata.get('links', [])[-1] if metadata.get('links') else ''
        })

# 메타데이터 정보를 데이터프레임으로 변환
dataframe = pd.DataFrame(metadata_list)

# 데이터프레임 확인
print(dataframe)

# 데이터프레임 저장 (선택 사항)
output_path = "arxiv_metadata.csv"
dataframe.to_csv(output_path, index=False, encoding='utf-8-sig')
print(f"Metadata saved to {output_path}")

               Query                                              Title  \
0         cat : cs.*  Barut-Girardello coherent states for sp(N,C) a...
1         cat : cs.*  Demonstrating CAT: Synthesizing Data-Aware Con...
2         cat : cs.*             Undirected Cat-and-Mouse is P-complete
3       cat : math.*  Random groups have fixed points on CAT(0) cube...
4       cat : math.*  Low-dimensional representations of matrix grou...
5       cat : math.*                                       Hydra groups
6    cat : physics.*  Is it possible to suspend the spread of an epi...
7    cat : physics.*                         Free Will and Falling Cats
8    cat : physics.*                    A Requiem For Schrödinger's Cat
9       cat : eess.*  CAT: A CTC-CRF based ASR Toolkit Bridging the ...
10      cat : eess.*                         CAT: CRF-based ASR Toolkit
11      cat : eess.*  Assessing the Circadian Rhythm of Cats Living ...
12      cat : econ.*  Sequential Choices, Option Values, and the Ret...
13      cat : econ.*   A matrix pencil approach to the Morgan's problem
14      cat : econ.*      Local Projection Inference in High Dimensions
15     cat : q-bio.*                  Semistability and CAT(0) Geometry
16     cat : q-bio.*                              Quantum Mona Lisa Cat
17     cat : q-bio.*              On the Topological Complexity of Maps
18      cat : q-fin*  The Construction of Instruction-tuned LLMs for...
19      cat : q-fin*                  Semistability and CAT(0) Geometry
20      cat : q-fin*                              Quantum Mona Lisa Cat
21       cat : stat*  The Intrinsic Shape Distribution of a Sample o...
22       cat : stat*  $ωN$ scattering length from $ω$ photoproductio...
23       cat : stat*             Multi view stereo with semantic priors
24  cat : astro-ph.*  Trojan pairs in the HD 128311 and HD 82943 pla...
25  cat : astro-ph.*  Density Profiles of Collisionless Equilibria. ...
26  cat : astro-ph.*  Properties of Microlensing Light Curve Anomali...

                                              Summary  \
0   Overcomplete families of states of the type of...
1   Databases for OLTP are often the backbone for ...
2   Cat-and-mouse is a two-player game on a finite...
3   We prove that a random group has fixed points ...
4   We study low-dimensional representations of ma...
5   We give examples of CAT(0), biautomatic, free-...
6   We study a dynamics of the epidemiological inf...
7   If we consider a cat to be an isolated mechani...
8   It is pointed out that Schr\"odinger's celebra...
9   In this paper, we present a new open source to...
10  In this paper, we present a new open source to...
11  This study explores the biological rhythms of ...
12  Using detailed Norwegian data on earnings, edu...
13  The problem of decoupling a nonsquare state sp...
14  In this paper, we estimate impulse responses b...
15  We explain why semistability of a one-ended pr...
16  Schr\"{o}dinger's Cat was proposed by Erwin Sc...
17  We define and develop a homotopy invariant not...
18  This paper proposes a novel method for constru...
19  We explain why semistability of a one-ended pr...
20  Schr\"{o}dinger's Cat was proposed by Erwin Sc...
21  We apply the dynamical modeling approach of St...
22  Photoproduction of the $\omega$ meson on the p...
23  Patch-based stereo is nowadays a commonly used...
24  Two nearby stars, HD 128311 and HD 82943, are ...
25  We investigate the connection between collisio...
26  In this paper, we show that the pattern of mic...

                                   PDF Link
0   http://arxiv.org/pdf/quant-ph/9706028v1
1         http://arxiv.org/pdf/2203.14144v1
2         http://arxiv.org/pdf/1511.00984v1
3          http://arxiv.org/pdf/1012.4147v1
4          http://arxiv.org/pdf/1207.6747v1
5          http://arxiv.org/pdf/1002.1945v2
6         http://arxiv.org/pdf/2005.14320v1
7         http://arxiv.org/pdf/2405.04565v1
8          http://arxiv.org/pdf/1208.4375v1
9         http://arxiv.org/pdf/2005.13326v2
10        http://arxiv.org/pdf/1911.08747v1
11        http://arxiv.org/pdf/2410.06594v1
12        http://arxiv.org/pdf/2205.05444v2
13        http://arxiv.org/pdf/2401.07157v1
14        http://arxiv.org/pdf/2209.03218v3
15        http://arxiv.org/pdf/1703.07003v1
16        http://arxiv.org/pdf/2001.10184v2
17        http://arxiv.org/pdf/2011.10646v1
18        http://arxiv.org/pdf/2409.19854v1
19        http://arxiv.org/pdf/1703.07003v1
20        http://arxiv.org/pdf/2001.10184v2
21  http://arxiv.org/pdf/astro-ph/0003468v1
22        http://arxiv.org/pdf/1904.02797v2
23        http://arxiv.org/pdf/2007.02295v1
24  http://arxiv.org/pdf/astro-ph/0510109v2
25  http://arxiv.org/pdf/astro-ph/0510332v2
26  http://arxiv.org/pdf/astro-ph/0107517v1
Metadata saved to arxiv_metadata.csv

In [ ]:
# Langchain 기반 Loader 설정 확인
from langchain.document_loaders import ArxivLoader
#help(ArxivLoader)

#!pip show langchain

In [ ]:
# Test

import requests
import xml.etree.ElementTree as ET

# ArXiv API URL 구성
url = "http://export.arxiv.org/api/query"
params = {
    "search_query": "cat:q-bio.*",
    "start": 0,
    "max_results": 50
}
response = requests.get(url, params=params)

# API 응답 확인
print(response.status_code)  # 응답 코드 (200이어야 정상)
#print(response.text)         # 응답 내용 출력

# XML 응답 파싱
root = ET.fromstring(response.text)
entries = root.findall('{http://www.w3.org/2005/Atom}entry')

# 논문 메타데이터 추출
metadata_list = []
for entry in entries:
    title = entry.find('{http://www.w3.org/2005/Atom}title').text
    summary = entry.find('{http://www.w3.org/2005/Atom}summary').text
    pdf_link = None
    for link in entry.findall('{http://www.w3.org/2005/Atom}link'):
        if link.attrib.get('title') == 'pdf':
            pdf_link = link.attrib['href']
            break
    metadata_list.append({'Title': title, 'Summary': summary, 'PDF Link': pdf_link})

# 결과 출력
for meta in metadata_list:
    print(meta)

print(f'len : {len(metadata_list)}')

200
{'Title': 'Acto-myosin clusters as active units shaping living matter', 'Summary': '  Stress generation by the actin cytoskeleton shapes cells and tissues. Despite\nimpressive progress in live imaging and quantitative physical descriptions of\ncytoskeletal network dynamics, the connection between processes at molecular\nscales and cell-scale spatio-temporal patterns is still unclear. Here we review\nstudies reporting acto-myosin clusters of micrometer size and with lifetimes of\nseveral minutes in a large number of organisms ranging from fission yeast to\nhumans. Such structures have also been found in reconstituted systems in vitro\nand in theoretical analysis of cytoskeletal dynamics. We propose that tracking\nthese clusters can serve as a simple readout for characterising living matter.\nSpatio-temporal patterns of clusters could serve as determinants of\nmorphogenetic processes that play similar roles in diverse organisms.\n', 'PDF Link': 'http://arxiv.org/pdf/2408.05119v1'}
{'Title': 'Genome-scale reconstruction of the metabolic network in Yersinia pestis,\n  strain 91001', 'Summary': '  The gram-negative bacterium Yersinia pestis, the aetiological agent of\nbubonic plague, is one the deadliest pathogens known to man. Despite its\nhistorical reputation, plague is a modern disease which annually afflicts\nthousands of people. Public safety considerations greatly limit clinical\nexperimentation on this organism and thus development of theoretical tools to\nanalyze the capabilities of this pathogen is of utmost importance. Here, we\nreport the first genome-scale metabolic model of Yersinia pestis biovar\nMediaevalis based both on its recently annotated genome, and physiological and\nbiochemical data from literature. Our model demonstrates excellent agreement\nwith Y. pestis known metabolic needs and capabilities. Since Y. pestis is a\nmeiotrophic organism, we have developed CryptFind, a systematic approach to\nidentify all candidate cryptic genes responsible for known and theoretical\nmeiotrophic phenomena. In addition to uncovering every known cryptic gene for\nY. pestis, our analysis of the rhamnose fermentation pathway suggests that betB\nis the responsible cryptic gene. Despite all of our medical advances, we still\ndo not have a vaccine for bubonic plague. Recent discoveries of antibiotic\nresistant strains of Yersinia pestis coupled with the threat of plague being\nused as a bioterrorism weapon compel us to develop new tools for studying the\nphysiology of this deadly pathogen. Using our theoretical model, we can study\nthe cells phenotypic behavior under different circumstances and identify\nmetabolic weaknesses which may be harnessed for the development of\ntherapeutics. Additionally, the automatic identification of cryptic genes\nexpands the usage of genomic data for pharmaceutical purposes.\n', 'PDF Link': 'http://arxiv.org/pdf/0903.4219v1'}
{'Title': 'Infer metabolic velocities from moment differences of molecular weight\n  distributions', 'Summary': '  Metabolic pathways are fundamental maps in biochemistry that detail how\nmolecules are transformed through various reactions. The complexity of\nmetabolic network, where a single compound can play a part in multiple\npathways, poses a challenge in inferring metabolic balance changes over time or\nafter different treatments. Isotopic labeling experiment is the standard method\nto infer metabolic flux, which is currently defined as the flow of a single\nmetabolite through a given pathway over time. However, there is still no way to\naccurately infer the metabolic balance changes after different treatments in an\nexperiment. This study introduces a different concept: molecular weight\ndistribution, which is the empirical distribution of the molecular weights of\nall metabolites of interest. By estimating the differences of the location and\nscale estimates of these distributions, it becomes possible to quantitatively\ninfer the metabolic balance changes even without requiring knowledge of the\nexact chemical structures of these compounds and their related pathways. This\nresearch article provides a mathematical framing for a classic biological\nconcept.\n', 'PDF Link': 'http://arxiv.org/pdf/2402.14887v4'}
{'Title': 'Spatial cancer systems biology resolves heterotypic interactions and\n  identifies disruption of spatial hierarchy as a pathological driver event', 'Summary': '  Spatially annotated single-cell datasets provide unprecedented opportunities\nto dissect cell-cell communication in development and disease. Heterotypic\nsignaling includes interactions between different cell types and is well\nestablished in tissue development and spatial organization. Epithelial\norganization requires several different programs that are tightly regulated.\nPlanar cell polarity is the organization of epithelial cells along the planar\naxis orthogonal to the apical-basal axis. In this study, we investigate planar\ncell polarity factors and explore the implications of developmental regulators\nas malignant drivers. Utilizing cancer systems biology analysis, we derive gene\nexpression network for WNT-ligands (WNT) and their cognate frizzled (FZD)\nreceptors in skin cutaneous melanoma. The profiles supported by unsupervised\nclustering of multiple-sequence alignments identify ligand-independent\nsignaling and implications for metastatic progression based on the underpinning\ndevelopmental spatial program. Omics studies and spatial biology connect\ndevelopmental programs with oncological events and explain key spatial features\nof metastatic aggressiveness. Dysregulation of prominent planar cell polarity\nfactors such specific representative of the WNT and FZD families in malignant\nmelanoma recapitulates the development program of normal melanocytes but in an\nuncontrolled and disorganized fashion.\n', 'PDF Link': 'http://arxiv.org/pdf/2303.00933v1'}
{'Title': 'Prediction of cellular burden with host-circuit models', 'Summary': '  Heterologous gene expression draws resources from host cells. These resources\ninclude vital components to sustain growth and replication, and the resulting\ncellular burden is a widely recognised bottleneck in the design of robust\ncircuits. In this tutorial we discuss the use of computational models that\nintegrate gene circuits and the physiology of host cells. Through various use\ncases, we illustrate the power of host-circuit models to predict the impact of\ndesign parameters on both burden and circuit functionality. Our approach relies\non a new generation of computational models for microbial growth that can\nflexibly accommodate resource bottlenecks encountered in gene circuit design.\nAdoption of this modelling paradigm can facilitate fast and robust design\ncycles in synthetic biology.\n', 'PDF Link': 'http://arxiv.org/pdf/2004.00995v2'}
{'Title': 'New Approaches in Synthetic Biology: Abiotic Organelles and Artificial\n  Cells Powered and Controlled by Light', 'Summary': '  One of the major goals of nanobionics and bottom-up synthetic biology is the\ndevelopment of artificial cell organelles for the creation of cell-like\nstructures operating similar to biological systems with a minimalistic set of\nbuilding blocks. In the present contribution, versatile strategies to develop\nartificial reaction centers for novel photoautotrophic processes and to provide\nfully biocompatible synthetic enzyme counterparts for stepwise sustrate\nphoto-conversion in abiotic organelles are summarized. This unique approach has\nthe potential to create artificial cell-like systems that can be readily\nmanipulated by light providing both energy input and fundamental regulatory\nfunctions.\n', 'PDF Link': 'http://arxiv.org/pdf/1911.06684v1'}
{'Title': 'Modelling the Role of Nitric Oxide in Cerebral Autoregulation', 'Summary': '  Malfunction of the system which regulates the bloodflow in the brain is a\nmajor cause of stroke and dementia, costing many lives and many billions of\npounds each year in the UK alone. This regulatory system, known as cerebral\nautoregulation, has been the subject of much experimental and mathematical\ninvestigation yet our understanding of it is still quite limited. One area in\nwhich our understanding is particularly lacking is that of the role of nitric\noxide, understood to be a potent vasodilator. The interactions of nitric oxide\nwith the better understood myogenic response remain un-modelled and poorly\nunderstood. In this thesis we present a novel model of the arteriolar control\nmechanism, comprising a mixture of well-established and new models of\nindividual processes, brought together for the first time. We show that this\nmodel is capable of reproducing experimentally observed behaviour very closely\nand go on to investigate its stability in the context of the vasculature of the\nwhole brain. In conclusion we find that nitric oxide, although it plays a\ncentral role in determining equilibrium vessel radius, is unimportant to the\ndynamics of the system and its responses to variation in arterial blood\npressure. We also find that the stability of the system is very sensitive to\nthe dynamics of Ca$^{2+}$ within the muscle cell, and that self-sustaining\nCa$^{2+}$ waves are not necessary to cause whole-vessel radius oscillations\nconsistent with vasomotion.\n', 'PDF Link': 'http://arxiv.org/pdf/1512.09160v1'}
{'Title': 'Fundamentally different strategies for transcriptional regulation are\n  revealed by information-theoretical analysis of binding motifs', 'Summary': '  To regulate a particular gene, a transcription factor (TF) needs to bind a\nspecific genome location. How is this genome address specified amid the\npresence of ~10^6-10^9 decoy sites? Our analysis of 319 known TF binding motifs\nclearly demonstrates that prokaryotes and eukaryotes use strikingly different\nstrategies to target TFs to specific genome locations; eukaryotic TFs exhibit\nwidespread nonfunctional binding and require clustering of sites in regulatory\nregions for specificity.\n', 'PDF Link': 'http://arxiv.org/pdf/0812.3910v3'}
{'Title': 'Lipidomic approach for stratification of Acute Myeloid Leukemia patients', 'Summary': '  The pathogenesis and progression of many tumors, including hematologic\nmalignancies is highly dependent on enhanced lipogenesis. De novo fatty-acid\nsynthesis permits accelerated proliferation of tumor cells by providing\nstructural components to build the membranes. It may also lead to alterations\nof physicochemical properties of the formed membranes, which can have an impact\non signaling or even increase resistance to drugs in cancer cells. Cancer\ntype-specific lipid profiles would allow understanding the actual effects of\nlipid changes and therefore could potentially serve as fingerprints for\nindividual tumors and be explored as diagnostic markers. We have used shotgun\nMS approach to identify lipid patterns in different types of acute myeloid\nleukemia (AML) patients that either show no karyotype changes or belong to\nt(8;21) or inv16 types. The observed differences in lipidomes of t(8;21) and\ninv(16) patients, as compared to AML patients without karyotype changes,\nconcentrate mostly on substantial modulation of ceramides/sphingolipids\nsynthesis. Also significant changes in the physicochemical properties of the\nmembranes, between the t(8;21) and the other patients, were noted that were\nrelated to a marked alteration in the saturation levels of lipids. The revealed\ndifferences in lipid profiles of various AML types increase our understanding\nof the affected biochemical pathways and can potentially serve as diagnostic\ntools.\n', 'PDF Link': 'http://arxiv.org/pdf/1611.10042v1'}
{'Title': 'Differential stoichiometry among core ribosomal proteins', 'Summary': '  Understanding the regulation and structure of ribosomes is essential to\nunderstanding protein synthesis and its deregulation in disease. While\nribosomes are believed to have a fixed stoichiometry among their core ribosomal\nproteins (RPs), some experiments suggest a more variable composition. Testing\nsuch variability requires direct and precise quantification of RPs. We used\nmass-spectrometry to directly quantify RPs across monosomes and polysomes of\nmouse embryonic stem cells (ESC) and budding yeast. Our data show that the\nstoichiometry among core RPs in wild-type yeast cells and ESC depends both on\nthe growth conditions and on the number of ribosomes bound per mRNA.\nFurthermore, we find that the fitness of cells with a deleted RP-gene is\ninversely proportional to the enrichment of the corresponding RP in polysomes.\nTogether, our findings support the existence of ribosomes with distinct protein\ncomposition and physiological function.\n', 'PDF Link': 'http://arxiv.org/pdf/1406.0399v2'}
{'Title': 'Digital clocks: simple Boolean models can quantitatively describe\n  circadian systems', 'Summary': "  The gene networks that comprise the circadian clock modulate biological\nfunction across a range of scales, from gene expression to performance and\nadaptive behaviour. The clock functions by generating endogenous rhythms that\ncan be entrained to the external 24-h day?night cycle, enabling organisms to\noptimally time biochemical processes relative to dawn and dusk. In recent\nyears, computational models based on differential equations have become useful\ntools for dissecting and quantifying the complex regulatory relationships\nunderlying the clock's oscillatory dynamics. However, optimizing the large\nparameter sets characteristic of these models places intense demands on both\ncomputational and experimental resources, limiting the scope of in silico\nstudies. Here, we develop an approach based on Boolean logic that dramatically\nreduces the parametrization, making the state and parameter spaces finite and\ntractable. We introduce efficient methods for fitting Boolean models to\nmolecular data, successfully demonstrating their application to synthetic time\ncourses generated by a number of established clock models, as well as\nexperimental expression levels measured using luciferase imaging. Our results\nindicate that despite their relative simplicity, logic models can (i) simulate\ncircadian oscillations with the correct, experimentally observed phase\nrelationships among genes and (ii) flexibly entrain to light stimuli,\nreproducing the complex responses to variations in daylength generated by more\ndetailed differential equation formulations. Our work also demonstrates that\nlogic models have sufficient predictive power to identify optimal regulatory\nstructures from experimental data. By presenting the first Boolean models of\ncircadian circuits together with general techniques for their optimization, we\nhope to establish a new framework for the systematic modelling of complex\nclocks.\n", 'PDF Link': 'http://arxiv.org/pdf/1210.6482v1'}
{'Title': 'The Role of the Hes1 Crosstalk Hub in Notch-Wnt Interactions of the\n  Intestinal Crypt', 'Summary': "  The Notch pathway plays a vital role in determining whether cells in the\nintestinal epithelium adopt a secretory or an absorptive phenotype. Cell fate\nspecification is coordinated via Notch's interaction with the canonical Wnt\npathway. Here, we propose a new mathematical model of the Notch and Wnt\npathways, in which the Hes1 promoter acts as a hub for pathway crosstalk.\nComputational simulations of the model can assist in understanding how healthy\nintestinal tissue is maintained, and predict the likely consequences of\nbiochemical knockouts upon cell fate selection processes. Chemical reaction\nnetwork theory (CRNT) is a powerful, generalised framework which assesses the\ncapacity of our model for monostability or multistability, by analysing\nproperties of the underlying network structure without recourse to specific\nparameter values or functional forms for reaction rates. CRNT highlights the\nrole of beta-catenin in stabilising the Notch pathway and damping oscillations,\ndemonstrating that Wnt-mediated actions on the Hes1 promoter can induce\ndynamical transitions in the Notch system, from multistability to\nmonostability. Time-dependent model simulations of cell pairs reveal the\nstabilising influence of Wnt upon the Notch pathway, in which beta-catenin- and\nDsh-mediated action on the Hes1 promoter are key in shaping the subcellular\ndynamics. Where Notch-mediated transcription of Hes1 dominates, there is Notch\noscillation and maintenance of fate flexibility; Wnt-mediated transcription of\nHes1 favours bistability akin to cell fate selection. Cells could therefore\nregulate the proportion of Wnt- and Notch-mediated control of the Hes1 promoter\nto coordinate the timing of cell fate selection as they migrate through the\nintestinal epithelium and are subject to reduced Wnt stimuli.\n", 'PDF Link': 'http://arxiv.org/pdf/1608.06146v1'}
{'Title': 'A matter of time: Using dynamics and theory to uncover mechanisms of\n  transcriptional bursting', 'Summary': '  Eukaryotic transcription generally occurs in bursts of activity lasting\nminutes to hours; however, state-of-the-art measurements have revealed that\nmany of the molecular processes that underlie bursting, such as transcription\nfactor binding to DNA, unfold on timescales of seconds. This temporal\ndisconnect lies at the heart of a broader challenge in physical biology of\npredicting transcriptional outcomes and cellular decision-making from the\ndynamics of underlying molecular processes. Here, we review how new dynamical\ninformation about the processes underlying transcriptional control can be\ncombined with theoretical models that predict not only averaged transcriptional\ndynamics, but also their variability, to formulate testable hypotheses about\nthe molecular mechanisms underlying transcriptional bursting and control.\n', 'PDF Link': 'http://arxiv.org/pdf/2008.09225v2'}
{'Title': 'Closing the Loop on Morphogenesis: A Mathematical Model of Morphogenesis\n  by Closed-Loop Reaction-Diffusion', 'Summary': '  Morphogenesis, the establishment and repair of emergent complex anatomy by\ngroups of cells, is a fascinating and biomedically-relevant problem. One of its\nmost fascinating aspects is that a developing embryo can reliably recover from\ndisturbances, such as splitting into twins. While this reliability implies some\ntype of goal-seeking error minimization over a morphogenic field, there are\nmany gaps with respect to detailed, constructive models of such a process being\nused to implement the collective intelligence of cellular swarms. We describe a\nclosed-loop negative-feedback system for creating reaction-diffusion (RD)\npatterns with high reliability. It uses a cellular automaton to characterize a\nmorphogen pattern, then compares it to a goal and adjusts accordingly,\nproviding a framework for modeling anatomical homeostasis and robust generation\nof target morphologies. Specifically, we create a RD pattern with N\nrepetitions, where N is easily changeable. Furthermore, the individual\nrepetitions of the RD pattern can be easily stretched or shrunk under genetic\ncontrol to create, e.g., some morphological features larger than others.\nFinally, the cellular automaton uses a computation wave that scans the\nmorphogen pattern unidirectionally to characterize the features that the\nnegative feedback then controls. By taking advantage of a prior process\nasymmetrically establishing planar polarity (e.g., head vs. tail), our\nautomaton is greatly simplified. This work contributes to the exciting effort\nof understanding design principles of morphological computation, which can be\nused to understand evolved developmental mechanisms, manipulate them in\nregenerative medicine settings, or embed a degree of synthetic intelligence\ninto novel bioengineered constructs.\n', 'PDF Link': 'http://arxiv.org/pdf/2211.01313v1'}

50

In [ ]:
df_bio_metadata_list = pd.DataFrame(metadata_list)
print(len(df_bio_metadata_list))
df_bio_metadata_list.head()

50

,Title,Summary,PDF Link
0,Acto-myosin clusters as active units shaping l...,Stress generation by the actin cytoskeleton ...,http://arxiv.org/pdf/2408.05119v1
1,Genome-scale reconstruction of the metabolic n...,"The gram-negative bacterium Yersinia pestis,...",http://arxiv.org/pdf/0903.4219v1
2,Infer metabolic velocities from moment differe...,Metabolic pathways are fundamental maps in b...,http://arxiv.org/pdf/2402.14887v4
3,Spatial cancer systems biology resolves hetero...,Spatially annotated single-cell datasets pro...,http://arxiv.org/pdf/2303.00933v1
4,Prediction of cellular burden with host-circui...,Heterologous gene expression draws resources...,http://arxiv.org/pdf/2004.00995v2

In [2]:
#!pip install -qU langchain-community arxiv pymupdf pdf2image pypdf PyPDF2

In [56]:
# 전체 카테고리 (API 활용 방식)
import os
import pandas as pd
from langchain.document_loaders import ArxivLoader
from langchain.document_loaders import PyPDFLoader
from pdf2image import convert_from_path
from huggingface_hub import hf_hub_download
#import cv2
#from doclayout_yolo import YOLOv10
from PIL import Image
import time
import requests
import xml.etree.ElementTree as ET
from PyPDF2 import PdfReader
import io

# ArXiv API URL 구성
url = "http://export.arxiv.org/api/query"

# Query 리스트와 최대 문서 수 정의
# 쿼리 리스트 및 각 쿼리에 따른 최대 문서 수 설정
queries = ["cat : cs.*", "cat : math.*", "cat : physics.*", "cat : eess.*", "cat : econ.*", "cat : q-bio.*", "cat : q-fin.*", "cat : stat.*", "cat : astro-ph.*"]
load_max_docs_list = [5, 5, 5, 5, 5, 5, 5, 5, 5]  # 9개의 category이므로 우선 5개씩 저장해서 활용

#### 본문 저장하기 위한 함수 (PdfReader)
"""
def extract_text_from_pdf(pdf_url):
    try:
        response = requests.get(pdf_url)
        response.raise_for_status()  # 요청 성공 여부 확인

        with io.BytesIO(response.content) as pdf_file:
            reader = PdfReader(pdf_file)
            text = ""
            for page in reader.pages:
                text += page.extract_text()
        return text
    except Exception as e:
        print(f"Error extracting text from {pdf_url}: {e}")
        return None
"""
#### 본문 반영 (arxivloader 반영)
def apply_arxiv_content(row):
    '''
    아래 metadata에서 본문 반영(arxivloader 사용)
    '''
    try:
        loader = ArxivLoader(query=row, load_max_docs=1, load_all_available_meta=True)
        docs = loader.load()
        time.sleep(1)
        if docs:
            return docs[0].metadata  # 메타데이터만 반환
    except Exception as e:
        print(f"Error loading metadata for '{title}': {e}")
        return None

# 메타데이터 저장
metadata_list = []

for query, max_docs in zip(queries, load_max_docs_list):
    params = {
        "search_query": query,
        "start": 0,
        "max_results": max_docs
    }

    response = requests.get(url, params=params)

    # API 응답 확인
    if response.status_code != 200:
        print(f"Error: Failed to fetch data for query '{query}' with status code {response.status_code}")
        continue

    # XML 응답 파싱
    root = ET.fromstring(response.text)
    entries = root.findall('{http://www.w3.org/2005/Atom}entry')

    # 논문 메타데이터 추출
    category = query.split(':')[1].split('.')[0]  # 'cat:' 이후, '.' 이전 부분 추출

    # 논문 메타데이터 추출
    for entry in entries:
        title = entry.find('{http://www.w3.org/2005/Atom}title').text
        summary = entry.find('{http://www.w3.org/2005/Atom}summary').text
        pdf_link = None
        for link in entry.findall('{http://www.w3.org/2005/Atom}link'):
            if link.attrib.get('title') == 'pdf':
                pdf_link = link.attrib['href']
                break

        metadata_list.append({
            'Category': category,
            'Query': query,
            'Title': title,
            'Summary': summary,
            'PDF Link': pdf_link,
        })

        # PDF 본문 추출 (PdfReader 일 때)
        #pdf_text = extract_text_from_pdf(pdf_link) if pdf_link else None

# 결과 출력
for meta in metadata_list:
    print(meta)

print(f'Total number of papers fetched: {len(metadata_list)}')

{'Category': ' cs', 'Query': 'cat : cs.*', 'Title': 'Brittle System Analysis', 'Summary': '  The goal of this paper is to define and analyze systems which exhibit brittle\nbehavior. This behavior is characterized by a sudden and steep decline in\nperformance as the system approaches the limits of tolerance. This can be due\nto input parameters which exceed a specified input, or environmental conditions\nwhich exceed specified operating boundaries. An analogy is made between brittle\ncommmunication systems in particular and materials science.\n', 'PDF Link': 'http://arxiv.org/pdf/cs/9904016v1'}
{'Category': ' cs', 'Query': 'cat : cs.*', 'Title': 'The Unix KISS: A Case Study', 'Summary': '  In this paper we show that the initial philosophy used in designing and\ndeveloping UNIX in early times has been forgotten due to "fast practices". We\nquestion the leitmotif that microkernels, though being by design adherent to\nthe KISS principle, have a number of context switches higher than their\nmonolithic counterparts, running a test suite and verify the results with\nstandard statistical validation tests. We advocate a wiser distribution of\nshared libraries by statistically analyzing the weight of each shared object in\na typical UNIX system, showing that the majority of shared libraries exist in a\ncommon space for no real evidence of need. Finally we examine the UNIX heritage\nwith an historical point of view, noticing how habits swiftly replaced the\nintents of the original authors, moving the focus from the earliest purpose of\nis avoiding complications, keeping a system simple to use and maintain.\n', 'PDF Link': 'http://arxiv.org/pdf/cs/0701021v2'}
{'Category': ' cs', 'Query': 'cat : cs.*', 'Title': 'ASC-Hook: fast and transparent system call hook for Arm', 'Summary': '  Intercepting system calls is crucial for tools that aim to modify or monitor\napplication behavior. However, existing system call interception tools on the\nARM platform still suffer from limitations in terms of performance and\ncompleteness. This paper presents an efficient and comprehensive binary\nrewriting framework, ASC-Hook, specifically designed for intercepting system\ncalls on the ARM platform. ASC-Hook addresses two key challenges on the ARM\narchitecture: the misalignment of the target address caused by directly\nreplacing the SVC instruction with br x8, and the return to the original\ncontrol flow after system call interception. This is achieved through a hybrid\nreplacement strategy and our specially designed trampoline mechanism. By\nimplementing multiple completeness strategies specifically for system calls, we\nensured comprehensive and thorough interception. Experimental results show that\nASC-Hook reduces overhead to at least 1/29 of that of existing system call\ninterception tools. We conducted extensive performance evaluations of ASC-Hook,\nand the average performance loss for system call-intensive applications is\n3.7\\% .\n', 'PDF Link': 'http://arxiv.org/pdf/2412.05784v3'}
{'Category': ' cs', 'Query': 'cat : cs.*', 'Title': 'Learnings from an Under the Hood Analysis of an Object Storage Node IO\n  Stack', 'Summary': '  Conventional object-stores are built on top of traditional OS storage stack,\nwhere I/O requests typically transfers through multiple hefty and redundant\nlayers. The complexity of object management has grown dramatically with the\never increasing requirements of performance, consistency and fault-tolerance\nfrom storage subsystems. Simply stated, more number of intermediate layers are\nencountered in the I/O data path, with each passing layer adding its own syntax\nand semantics. Thereby increasing the overheads of request processing. In this\npaper, through comprehensive under-the-hood analysis of an object-storage node,\nwe characterize the impact of object-store (and user-application) workloads on\nthe OS I/O stack and its subsequent rippling effect on the underlying\nobject-storage devices (OSD). We observe that the legacy architecture of the OS\nbased I/O storage stack coupled with complex data management policies leads to\na performance mismatch between what an end-storage device is capable of\ndelivering and what it actually delivers in a production environment.\nTherefore, the gains derived from developing faster storage devices is often\nnullified. These issues get more pronounced in highly concurrent and\nmultiplexed cloud environments. Owing to the associated issues of\nobject-management and the vulnerabilities of the OS I/O software stacks, we\ndiscuss the potential of a new class of storage devices, known as\nObject-Drives. Samsung Key-Value SSD (KV-SSD) [1] and Seagate Kinetic Drive [2]\nare classic industrial implementations of object-drives, where host data\nmanagement functionalities can be offloaded to the storage device. This leads\ntowards the simplification of the over-all storage stack. Based on our\nanalysis, we believe object-drives can alleviate object-stores from highly\ntaxing overheads of data management with 20-38% time-savings over traditional\nOperating Systems (OS) stack.\n', 'PDF Link': 'http://arxiv.org/pdf/2207.01849v1'}
{'Category': ' cs', 'Query': 'cat : cs.*', 'Title': 'An Example of Clifford Algebras Calculations with GiNaC', 'Summary': '  This example of Clifford algebras calculations uses GiNaC\n(http://www.ginac.de/) library, which includes a support for generic Clifford\nalgebra starting from version~1.3.0. Both symbolic and numeric calculation are\npossible and can be blended with other functions of GiNaC. This calculations\nwas made for the paper math.CV/0410399.\n  Described features of GiNaC are already available at PyGiNaC\n(http://sourceforge.net/projects/pyginac/) and due to course should propagate\ninto other software like GNU Octave (http://www.octave.org/), gTybalt\n(http://www.fis.unipr.it/~stefanw/gtybalt.html), which use GiNaC library as\ntheir back-end.\n', 'PDF Link': 'http://arxiv.org/pdf/cs/0410044v5'}
{'Category': ' math', 'Query': 'cat : math.*', 'Title': 'Generalized spaces for constructive algebra', 'Summary': '  The purpose of this contribution is to give a coherent account of a\nparticular narrative which links locales, geometric theories, sheaf semantics\nand constructive commutative algebra. We are hoping to convey a firm grasp of\nthree ideas: (1) Locales are a kind of space in which opens instead of points\nare fundamental. (2) Sheaf semantics allows us to explore mathematical objects\nfrom custom-tailored mathematical universes. (3) Without loss of generality,\nany reduced ring is a field.\n', 'PDF Link': 'http://arxiv.org/pdf/2012.13850v1'}
{'Category': ' math', 'Query': 'cat : math.*', 'Title': 'Constructing projective modules', 'Summary': '  We discuss elements of a social history of the theory of projective modules\nover commutative rings. We attempt to study the question: how did the theory of\nprojective modules become one of "mainstream" focus in mathematics? To do this,\nwe begin in what one might call the pre-history of projective modules,\ndescribing the mathematical culture into which the notion of projective module\nwas released. These recollections involve four pieces: (a) analyzing aspects of\nthe theory of fiber bundles, as it impinges on algebraic geometry, (b)\nunderstanding the rise of homological techniques in algebraic topology, (c)\ndescribing the influence of category-theoretic ideas in topology and algebra\nand (d) revisiting the story of the percolation of sheaf-theoretic ideas\nthrough algebraic geometry.\n  We will then argue that it was this unique confluence of mathematical events\nthat allowed projective modules to emerge as objects of central mathematical\nimportance. More precisely, we will first argue that, in the context of social\ncurrents of the time, projective modules initially were isolated as objects of\npurely technical convenience reflecting the aesthetic sensibilities of the\ncreators of the fledgling theory of homological algebra. Only later did they\ntranscend this limited role to become objects of "mainstream importance" due to\ninfluence from the theory of algebraic fiber bundles and the theory of sheaves.\nAlong the way, we aim to show how strong personal ties emanating from the\nBourbaki movement and its connections in mathematical centers including Paris,\nPrinceton and Chicago were essential to the entrance, propagation and\nmainstream mathematical acceptance of the theory.\n', 'PDF Link': 'http://arxiv.org/pdf/2412.05250v1'}
{'Category': ' math', 'Query': 'cat : math.*', 'Title': 'Quantalic spectra of semirings', 'Summary': "  Spectrum constructions appear throughout mathematics as a way of constructing\ntopological spaces from algebraic data. Given a commutative localic semiring R\n(the pointfree analogue of a topological semiring), we define a spectrum of R\nwhich generalises the Stone spectrum of a distributive lattice, the Zariski\nspectrum of a commutative ring, the Gelfand spectrum of a commutative unital\nC*-algebra and the Hofmann-Lawson spectrum of a continuous frame. We then\nprovide an explicit construction of this spectrum under conditions on R which\nare satisfied by our main examples.\n  Our results are constructively valid and hence admit interpretation in any\nelementary topos with natural number object. For this reason the spectrum we\nconstruct should actually be a locale instead of a topological space.\n  A simple modification to our construction gives rise to a quantic spectrum in\nthe form of a commutative quantale. Such a quantale contains `differential'\ninformation in addition to the purely topological information of the localic\nspectrum. In the case of a discrete ring, our construction produces the\nquantale of ideals.\n  This prompts us to study the quantale of ideals in more detail. We discuss\nsome results from abstract ideal theory in the setting of quantales and provide\na tentative definition for what it might mean for a quantale to be nonsingular\nby analogy to commutative ring theory.\n", 'PDF Link': 'http://arxiv.org/pdf/2201.06408v1'}
{'Category': ' math', 'Query': 'cat : math.*', 'Title': 'Von Neumann coordinatization is not first-order', 'Summary': '  A lattice L is coordinatizable, if it is isomorphic to the lattice L(R) of\nprincipal right ideals of some von Neumann regular ring R. This forces L to be\ncomplemented modular. All known sufficient conditions for coordinatizability,\ndue first to J. von Neumann, then to B. Jonsson, are first-order. Nevertheless,\nwe prove that coordinatizability of lattices is not first-order, by finding a\nnon-coordinatizable lattice K with a coordinatizable countable elementary\nextension L. This solves a 1960 problem of B. Jonsson. We also prove that there\nis no L\\_{infinity, infinity} statement equivalent to coordinatizability.\nFurthermore, the class of coordinatizable lattices is not closed under\ncountable directed unions; this solves another problem of B. Jonsson from 1962.\n', 'PDF Link': 'http://arxiv.org/pdf/math/0409250v3'}
{'Category': ' math', 'Query': 'cat : math.*', 'Title': 'Analysis in J_2', 'Summary': "  This is an expository paper in which I explain how core mathematics,\nparticularly abstract analysis, can be developed within a concrete countable\nset J_2 (the second set in Jensen's constructible hierarchy). The implication,\nwell-known to proof theorists but probably not to most mainstream\nmathematicians, is that ordinary mathematical practice does not require an\nenigmatic metaphysical universe of sets. I go further and argue that J_2 is a\nsuperior setting for normal mathematics because it is free of irrelevant\nset-theoretic pathologies and permits stronger formulations of existence\nresults.\n", 'PDF Link': 'http://arxiv.org/pdf/math/0509245v2'}
{'Category': ' physics', 'Query': 'cat : physics.*', 'Title': "German to Spanish translation of Einstein's work on the formation of\n  meanders in rivers", 'Summary': "  In 1926 Albert Einstein gave a clear explanation of the physical processes\ninvolved in the meander formation and evolution in open channels (Einstein,\n1926). Although this work is far from being recognized as one of his greatest\nachievements, such as his annus mirabilis papers in 1905, he shows a truly\nremarkable didactic skills that make it easy to understand even to the\nnon-specialist. In particular, a brilliant explanation of the tea leaf paradox\ncan be found in this paper of 1926, presented as a simple experiment for\nclarifying the role of Earth rotation and flow curvature in the differential\nriver banks erosion. This work deserves to be considered as a pioneering work\nthat has laid a basic knowledge in currently very active research fields in\nfluvial geomorphology, estuarine physics, and hydraulic engineering. In\nresponse to the curiosity aroused and transmitted to the authors over the years\nby undergraduates and MSc. students, and also due to its historical and\nscientific significance, we present here the Spanish translation of Einstein's\noriginal work published in German in 1926 in Die Naturwissenschaften (Einstein,\n1926). Einstein's drawings have not been interpreted, but just updated\npreserving their original spirit.\n", 'PDF Link': 'http://arxiv.org/pdf/2305.09528v1'}
{'Category': ' physics', 'Query': 'cat : physics.*', 'Title': 'Scientific Metaphors in the journalistic discourse', 'Summary': "  Scientific education and divulgation not only amplify people's vocabulary and\nrepertory of scientific concepts but, at the same time, promote the diffusion\nof certain conceptual and cognitive metaphors. Here we make some hypothesis\nabout this process, proposing a classification in terms of visible, invisible,\nbasic and derived metaphors. We focus our attention in contemporary and\nclassical physics metaphors applied to psychological and socio-economical\nphenomena, and we study two exemplar cases through an exhaustive exam of the\nonline content of large Brazilian journalistic portals. Finally, we present\nimplications and suggestions from the cognitive metaphor theory for the\nscientific education and divulgation process.\n", 'PDF Link': 'http://arxiv.org/pdf/1006.1128v3'}
{'Category': ' physics', 'Query': 'cat : physics.*', 'Title': 'How a fake Kepler portrait became iconic', 'Summary': '  For several decades a portrait of Johannes Kepler has been widely circulating\namong professional astronomers, scientific and academic institutions, and the\ngeneral public. Despite its provenance and identification having been\nquestioned in the early part of the last century, this painting has reached\niconic status. We review its history from its first mention in the literature\nin the 1870s to a published but virtually unknown judgment of competent art\nexperts of the 1920s that the work is in fact an early nineteenth century\nforgery. We display the painting in context with other more secure portraits\nand suggest that if it is based on anything, the painting may derive from the\nwell known portrait from life of Michael M\\"astlin. This correction takes on\ncertain urgency since 2021 is the 450th anniversary of Kepler\'s birth.\n', 'PDF Link': 'http://arxiv.org/pdf/2108.02213v3'}
{'Category': ' physics', 'Query': 'cat : physics.*', 'Title': 'Review Article: Integral Role of Physics in Advancing Pharmacy Education\n  and Research', 'Summary': "  Physics plays a fundamental role in advancing pharmacy education and\nresearch, providing theoretical underpinnings and practical tools necessary to\naddress complex challenges in drug development, delivery, and diagnostics. This\nreview explores the integration of physics into the pharmacy curriculum,\nhighlighting how principles such as fluid dynamics, thermodynamics, and\nspectroscopy (Tokgoz and Sakalli, 2018) enhance students' critical thinking and\nproblem-solving skills. Additionally, it examines the pivotal contributions of\nphysics to pharmaceutical research, including molecular modeling, imaging\ntechnologies like MRI and PET, and nanotechnology-driven drug delivery systems.\nDespite challenges in interdisciplinary collaboration and resource allocation,\ninnovative teaching strategies and laboratory based learning are shown\nsignificant promise. Looking forward, the convergence of artificial\nintelligence and physics, as highlighted by recent Nobel Prize achievements in\nattosecond physics and bioorthogonal chemistry, is set to revolutionize\npharmaceutical sciences, offering unprecedented precision and efficiency in\ndrug discovery and personalized medicine.\n", 'PDF Link': 'http://arxiv.org/pdf/2501.01527v1'}
{'Category': ' physics', 'Query': 'cat : physics.*', 'Title': 'Hollywood Blockbusters: Unlimited Fun but Limited Science Literacy', 'Summary': '  In this article, we examine specific scenes from popular action and sci-fi\nmovies and show how they blatantly break the laws of physics, all in the name\nof entertainment, but coincidentally contributing to science illiteracy.\n', 'PDF Link': 'http://arxiv.org/pdf/0707.1167v1'}
{'Category': ' eess', 'Query': 'cat : eess.*', 'Title': 'Unified Signal Compression Using a GAN with Iterative Latent\n  Representation Optimization', 'Summary': '  We propose a unified signal compression framework that uses a generative\nadversarial network (GAN) to compress heterogeneous signals. The compressed\nsignal is represented as a latent vector and fed into a generator network that\nis trained to produce high quality realistic signals that minimize a target\nobjective function. To efficiently quantize the compressed signal,\nnon-uniformly quantized optimal latent vectors are identified by iterative\nback-propagation with alternating direction method of multipliers (ADMM)\noptimization performed for each iteration. The performance of the proposed\nsignal compression method is assessed using multiple metrics including PSNR and\nMS-SSIM for image compression and also PESR, Kaldi, LSTM, and MLP performance\nfor speech compression. Test results show that the proposed work outperforms\nrecent state-of-the-art hand-crafted and deep learning-based signal compression\nmethods.\n', 'PDF Link': 'http://arxiv.org/pdf/2109.11168v1'}
{'Category': ' eess', 'Query': 'cat : eess.*', 'Title': 'Multi-Resolution Beta-Divergence NMF for Blind Spectral Unmixing', 'Summary': '  Many datasets are obtained as a resolution trade-off between two adversarial\ndimensions; for example between the frequency and the temporal resolutions for\nthe spectrogram of an audio signal, and between the number of wavelengths and\nthe spatial resolution for a hyper/multi-spectral image. To perform blind\nsource separation using observations with different resolutions, a standard\napproach is to use coupled nonnegative matrix factorizations (NMF). Most\nprevious works have focused on the least squares error measure, which is the\n$\\beta$-divergence for $\\beta = 2$. In this paper, we formulate this\nmulti-resolution NMF problem for any $\\beta$-divergence, and propose an\nalgorithm based on multiplicative updates (MU). We show on numerical\nexperiments that the MU are able to obtain high resolutions in both dimensions\non two applications: (1) blind unmixing of audio spectrograms: to the best of\nour knowledge, this is the first time a coupled NMF model is used in this\ncontext, and (2) the fusion of hyperspectral and multispectral images: we show\nthat the MU compete favorable with state-of-the-art algorithms in particular in\nthe presence of non-Gaussian noise.\n', 'PDF Link': 'http://arxiv.org/pdf/2007.03893v3'}

In [57]:
metadata_final = pd.DataFrame(metadata_list)
metadata_final['Title'] = metadata_final['Title'].astype(str)
metadata_final

,Category,Query,Title,Summary,PDF Link
0,cs,cat : cs.*,Brittle System Analysis,The goal of this paper is to define and anal...,http://arxiv.org/pdf/cs/9904016v1
1,cs,cat : cs.*,The Unix KISS: A Case Study,In this paper we show that the initial philo...,http://arxiv.org/pdf/cs/0701021v2
2,cs,cat : cs.*,ASC-Hook: fast and transparent system call hoo...,Intercepting system calls is crucial for too...,http://arxiv.org/pdf/2412.05784v3
3,cs,cat : cs.*,Learnings from an Under the Hood Analysis of a...,Conventional object-stores are built on top ...,http://arxiv.org/pdf/2207.01849v1
4,cs,cat : cs.*,An Example of Clifford Algebras Calculations w...,This example of Clifford algebras calculatio...,http://arxiv.org/pdf/cs/0410044v5
5,math,cat : math.*,Generalized spaces for constructive algebra,The purpose of this contribution is to give ...,http://arxiv.org/pdf/2012.13850v1
6,math,cat : math.*,Constructing projective modules,We discuss elements of a social history of t...,http://arxiv.org/pdf/2412.05250v1
7,math,cat : math.*,Quantalic spectra of semirings,Spectrum constructions appear throughout mat...,http://arxiv.org/pdf/2201.06408v1
8,math,cat : math.*,Von Neumann coordinatization is not first-order,"A lattice L is coordinatizable, if it is iso...",http://arxiv.org/pdf/math/0409250v3
9,math,cat : math.*,Analysis in J_2,This is an expository paper in which I expla...,http://arxiv.org/pdf/math/0509245v2
10,physics,cat : physics.*,German to Spanish translation of Einstein's wo...,In 1926 Albert Einstein gave a clear explana...,http://arxiv.org/pdf/2305.09528v1
11,physics,cat : physics.*,Scientific Metaphors in the journalistic disco...,Scientific education and divulgation not onl...,http://arxiv.org/pdf/1006.1128v3
12,physics,cat : physics.*,How a fake Kepler portrait became iconic,For several decades a portrait of Johannes K...,http://arxiv.org/pdf/2108.02213v3
13,physics,cat : physics.*,Review Article: Integral Role of Physics in Ad...,Physics plays a fundamental role in advancin...,http://arxiv.org/pdf/2501.01527v1
14,physics,cat : physics.*,Hollywood Blockbusters: Unlimited Fun but Limi...,"In this article, we examine specific scenes ...",http://arxiv.org/pdf/0707.1167v1
15,eess,cat : eess.*,Unified Signal Compression Using a GAN with It...,We propose a unified signal compression fram...,http://arxiv.org/pdf/2109.11168v1
16,eess,cat : eess.*,Multi-Resolution Beta-Divergence NMF for Blind...,Many datasets are obtained as a resolution t...,http://arxiv.org/pdf/2007.03893v3
17,eess,cat : eess.*,A multispeaker dataset of raw and reconstructe...,Real-time magnetic resonance imaging (RT-MRI...,http://arxiv.org/pdf/2102.07896v1
18,eess,cat : eess.*,SRIB-LEAP submission to Far-field Multi-Channe...,This paper presents the details of the SRIB-...,http://arxiv.org/pdf/2106.12763v1
19,eess,cat : eess.*,Deep Iterative Phase Retrieval for Ptychography,One of the most prominent challenges in the ...,http://arxiv.org/pdf/2202.10573v1
20,econ,cat : econ.*,Sectorial Exclusion Criteria in the Marxist An...,The long-term estimation of the Marxist aver...,http://arxiv.org/pdf/2501.06270v1
21,econ,cat : econ.*,A Practical Approach to Social Learning,Models of social learning feature either bin...,http://arxiv.org/pdf/2002.11017v1
22,econ,cat : econ.*,Identification of hedonic equilibrium and nons...,This paper derives conditions under which pr...,http://arxiv.org/pdf/1709.09570v6
23,econ,cat : econ.*,Revealed Price Preference: Theory and Empirica...,To determine the welfare implications of pri...,http://arxiv.org/pdf/1801.02702v3
24,econ,cat : econ.*,"Decision Conflict, Logit, and the Outside Option",Decision makers often opt for the deferral o...,http://arxiv.org/pdf/2008.04229v9
25,q-bio,cat : q-bio.*,Acto-myosin clusters as active units shaping l...,Stress generation by the actin cytoskeleton ...,http://arxiv.org/pdf/2408.05119v1
26,q-bio,cat : q-bio.*,Genome-scale reconstruction of the metabolic n...,"The gram-negative bacterium Yersinia pestis,...",http://arxiv.org/pdf/0903.4219v1
27,q-bio,cat : q-bio.*,Infer metabolic velocities from moment differe...,Metabolic pathways are fundamental maps in b...,http://arxiv.org/pdf/2402.14887v4
28,q-bio,cat : q-bio.*,Spatial cancer systems biology resolves hetero...,Spatially annotated single-cell datasets pro...,http://arxiv.org/pdf/2303.00933v1
29,q-bio,cat : q-bio.*,Prediction of cellular burden with host-circui...,Heterologous gene expression draws resources...,http://arxiv.org/pdf/2004.00995v2
30,q-fin,cat : q-fin.*,Efficient Pricing and Calibration of High-Dime...,This paper studies equity basket options -- ...,http://arxiv.org/pdf/2206.09877v1
31,q-fin,cat : q-fin.*,UNISWAP: Impermanent Loss and Risk Profile of ...,Uniswap is a decentralized exchange (DEX) an...,http://arxiv.org/pdf/2106.14404v1
32,q-fin,cat : q-fin.*,Pricing Financial Derivatives Subject to Count...,This article presents a generic model for pr...,http://arxiv.org/pdf/1804.02289v1
33,q-fin,cat : q-fin.*,"Randomization of Short-Rate Models, Analytic P...",We focus on extending existing short-rate mo...,http://arxiv.org/pdf/2211.05014v2
34,q-fin,cat : q-fin.*,Risk aggregation and capital allocation using ...,"In this paper, we address risk aggregation a...",http://arxiv.org/pdf/2103.10989v1
35,stat,cat : stat.*,KernSmoothIRT: An R Package for Kernel Smoothi...,Item response theory (IRT) models are a clas...,http://arxiv.org/pdf/1211.1183v2
36,stat,cat : stat.*,DBKGrad: An R Package for Mortality Rates Grad...,Kernel smoothing represents a useful approac...,http://arxiv.org/pdf/1211.1184v1
37,stat,cat : stat.*,Bayesian Quantile Regression for Longitudinal ...,This work introduces Bayesian quantile regre...,http://arxiv.org/pdf/2204.02344v1
38,stat,cat : stat.*,A practically efficient fixed-pivot selection ...,Many statistical problems and applications r...,http://arxiv.org/pdf/2302.05705v1
39,stat,cat : stat.*,A generalized Bayesian stochastic block model ...,Advances in next-generation sequencing techn...,http://arxiv.org/pdf/2308.14671v1
40,astro-ph,cat : astro-ph.*,Laboratory Astrophysics and the State of Astro...,Laboratory astrophysics and complementary th...,http://arxiv.org/pdf/0903.2469v1

In [58]:
metadata_final['Content'] = metadata_final['Title'].apply(apply_arxiv_content)
metadata_final

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

MuPDF error: syntax error: unknown keyword: 'ca'

Error fetching content for 'The Unix KISS: A Case Study': module 'fitz' has no attribute 'fitz'
MuPDF error: syntax error: unknown keyword: 'pagesize'

MuPDF error: syntax error: unknown keyword: 'width'

MuPDF error: syntax error: unknown keyword: '614.295pt'

MuPDF error: syntax error: unknown keyword: 'height'

MuPDF error: syntax error: unknown keyword: '794.96999pt'

,Category,Query,Title,Summary,PDF Link,Content
0,cs,cat : cs.*,Brittle System Analysis,The goal of this paper is to define and anal...,http://arxiv.org/pdf/cs/9904016v1,arXiv:cs/9904016v1 [cs.NI] 22 Apr 1999\nBUSH...
1,cs,cat : cs.*,The Unix KISS: A Case Study,In this paper we show that the initial philo...,http://arxiv.org/pdf/cs/0701021v2,None
2,cs,cat : cs.*,ASC-Hook: fast and transparent system call hoo...,Intercepting system calls is crucial for too...,http://arxiv.org/pdf/2412.05784v3,ASC-Hook: fast and transparent system call hoo...
3,cs,cat : cs.*,Learnings from an Under the Hood Analysis of a...,Conventional object-stores are built on top ...,http://arxiv.org/pdf/2207.01849v1,None
4,cs,cat : cs.*,An Example of Clifford Algebras Calculations w...,This example of Clifford algebras calculatio...,http://arxiv.org/pdf/cs/0410044v5,arXiv:cs/0410044v5 [cs.MS] 9 Dec 2005\narXiv...
5,math,cat : math.*,Generalized spaces for constructive algebra,The purpose of this contribution is to give ...,http://arxiv.org/pdf/2012.13850v1,arXiv:alg-geom/9708025v1 29 Aug 1997\nDuality...
6,math,cat : math.*,Constructing projective modules,We discuss elements of a social history of t...,http://arxiv.org/pdf/2412.05250v1,arXiv:1601.02737v1 [math.RT] 12 Jan 2016\nTH...
7,math,cat : math.*,Quantalic spectra of semirings,Spectrum constructions appear throughout mat...,http://arxiv.org/pdf/2201.06408v1,Q U A N TA L E S A N D H Y P E R S T R U C T U...
8,math,cat : math.*,Von Neumann coordinatization is not first-order,"A lattice L is coordinatizable, if it is iso...",http://arxiv.org/pdf/math/0409250v3,arXiv:1312.1663v1 [math.RA] 5 Dec 2013\nFrom...
9,math,cat : math.*,Analysis in J_2,This is an expository paper in which I expla...,http://arxiv.org/pdf/math/0509245v2,arXiv:cond-mat/9706078v1 [cond-mat.stat-mech]...
10,physics,cat : physics.*,German to Spanish translation of Einstein's wo...,In 1926 Albert Einstein gave a clear explana...,http://arxiv.org/pdf/2305.09528v1,None
11,physics,cat : physics.*,Scientific Metaphors in the journalistic disco...,Scientific education and divulgation not onl...,http://arxiv.org/pdf/1006.1128v3,Metáforas científicas no discurso jornalístico...
12,physics,cat : physics.*,How a fake Kepler portrait became iconic,For several decades a portrait of Johannes K...,http://arxiv.org/pdf/2108.02213v3,How a fake Kepler portrait became iconic\nStev...
13,physics,cat : physics.*,Review Article: Integral Role of Physics in Ad...,Physics plays a fundamental role in advancin...,http://arxiv.org/pdf/2501.01527v1,None
14,physics,cat : physics.*,Hollywood Blockbusters: Unlimited Fun but Limi...,"In this article, we examine specific scenes ...",http://arxiv.org/pdf/0707.1167v1,arXiv:0707.1167v1 [physics.soc-ph] 9 Jul 200...
15,eess,cat : eess.*,Unified Signal Compression Using a GAN with It...,We propose a unified signal compression fram...,http://arxiv.org/pdf/2109.11168v1,None
16,eess,cat : eess.*,Multi-Resolution Beta-Divergence NMF for Blind...,Many datasets are obtained as a resolution t...,http://arxiv.org/pdf/2007.03893v3,IEEE JSTARS\n1\nSparsity Constrained Distribut...
17,eess,cat : eess.*,A multispeaker dataset of raw and reconstructe...,Real-time magnetic resonance imaging (RT-MRI...,http://arxiv.org/pdf/2102.07896v1,None
18,eess,cat : eess.*,SRIB-LEAP submission to Far-field Multi-Channe...,This paper presents the details of the SRIB-...,http://arxiv.org/pdf/2106.12763v1,None
19,eess,cat : eess.*,Deep Iterative Phase Retrieval for Ptychography,One of the most prominent challenges in the ...,http://arxiv.org/pdf/2202.10573v1,Preprint prepared for Arxiv\nPTYCHOFORMER: A T...
20,econ,cat : econ.*,Sectorial Exclusion Criteria in the Marxist An...,The long-term estimation of the Marxist aver...,http://arxiv.org/pdf/2501.06270v1,None
21,econ,cat : econ.*,A Practical Approach to Social Learning,Models of social learning feature either bin...,http://arxiv.org/pdf/2002.11017v1,Social Practices: a Complete Formalization\nF....
22,econ,cat : econ.*,Identification of hedonic equilibrium and nons...,This paper derives conditions under which pr...,http://arxiv.org/pdf/1709.09570v6,None
23,econ,cat : econ.*,Revealed Price Preference: Theory and Empirica...,To determine the welfare implications of pri...,http://arxiv.org/pdf/1801.02702v3,A General Revealed Preference Test for Quasili...
24,econ,cat : econ.*,"Decision Conflict, Logit, and the Outside Option",Decision makers often opt for the deferral o...,http://arxiv.org/pdf/2008.04229v9,"Decision Conflict, Logit, and the Outside Opti..."
25,q-bio,cat : q-bio.*,Acto-myosin clusters as active units shaping l...,Stress generation by the actin cytoskeleton ...,http://arxiv.org/pdf/2408.05119v1,\n1 \nForecasting Avalanches in Branched Acto...
26,q-bio,cat : q-bio.*,Genome-scale reconstruction of the metabolic n...,"The gram-negative bacterium Yersinia pestis,...",http://arxiv.org/pdf/0903.4219v1,None
27,q-bio,cat : q-bio.*,Infer metabolic velocities from moment differe...,Metabolic pathways are fundamental maps in b...,http://arxiv.org/pdf/2402.14887v4,None
28,q-bio,cat : q-bio.*,Spatial cancer systems biology resolves hetero...,Spatially annotated single-cell datasets pro...,http://arxiv.org/pdf/2303.00933v1,None
29,q-bio,cat : q-bio.*,Prediction of cellular burden with host-circui...,Heterologous gene expression draws resources...,http://arxiv.org/pdf/2004.00995v2,Prediction of cellular burden with host-circui...
30,q-fin,cat : q-fin.*,Efficient Pricing and Calibration of High-Dime...,This paper studies equity basket options -- ...,http://arxiv.org/pdf/2206.09877v1,Eﬃcient Pricing and Calibration of High-Dimens...
31,q-fin,cat : q-fin.*,UNISWAP: Impermanent Loss and Risk Profile of ...,Uniswap is a decentralized exchange (DEX) an...,http://arxiv.org/pdf/2106.14404v1,UNISWAP: Impermanent Loss and Risk \nProfile o...
32,q-fin,cat : q-fin.*,Pricing Financial Derivatives Subject to Count...,This article presents a generic model for pr...,http://arxiv.org/pdf/1804.02289v1,None
33,q-fin,cat : q-fin.*,"Randomization of Short-Rate Models, Analytic P...",We focus on extending existing short-rate mo...,http://arxiv.org/pdf/2211.05014v2,None
34,q-fin,cat : q-fin.*,Risk aggregation and capital allocation using ...,"In this paper, we address risk aggregation a...",http://arxiv.org/pdf/2103.10989v1,None
35,stat,cat : stat.*,KernSmoothIRT: An R Package for Kernel Smoothi...,Item response theory (IRT) models are a clas...,http://arxiv.org/pdf/1211.1183v2,JSS\nKernSmoothIRT: An R Package for Kernel\nS...
36,stat,cat : stat.*,DBKGrad: An R Package for Mortality Rates Grad...,Kernel smoothing represents a useful approac...,http://arxiv.org/pdf/1211.1184v1,None
37,stat,cat : stat.*,Bayesian Quantile Regression for Longitudinal ...,This work introduces Bayesian quantile regre...,http://arxiv.org/pdf/2204.02344v1,Bayesian Quantile Regression for Longitudinal ...
38,stat,cat : stat.*,A practically efficient fixed-pivot selection ...,Many statistical problems and applications r...,http://arxiv.org/pdf/2302.05705v1,None
39,stat,cat : stat.*,A generalized Bayesian stochastic block model ...,Advances in next-generation sequencing techn...,http://arxiv.org/pdf/2308.14671v1,None
40,astro-ph,cat : astro-ph.*,Laboratory Astrophysics and the State of Astro...,Laboratory astrophysics and complementary th...,http://arxiv.org/pdf/0903.2469v1,Laboratory Astrophysics and the State of Astro...

In [52]:
metadata_final.loc[32]['Title']

'Pricing Financial Derivatives Subject to Counterparty Risk and Credit\n  Value Adjustment'

In [51]:
#### 오류 확인
apply_arxiv_content(metadata_final.loc[32])

Error loading metadata for 'Roles and Needs of Laboratory Astrophysics in NASA's Space and Earth
  Science Mission': 'Series' object has no attribute 'split'

- 실험 결과 case
  - None 발생되는 케이스
  - 결과값 논문 제목 들어있는 케이스
  - 논문 pdf 링크 들어있는 케이스 등 있음
  
- 결론
  - pdf 유형이 다를 경우의 가능성 있음.  
  - 대안 시도 가능 방안 : 그냥 pypdf 갖고 와서 텍스트 불러오고 전처리, abstract, 본론, 결론 등 나눠서 pdf 저장하는 방안.
  - 요약하고 결합하는 방식을 활용해야 하지 않을까 (요약시)
  - 요약 아닌 Q&A 경우 사용자 쿼리 따라 질의 유형 구분하고 적합한 위치 선정해 찾는 방안을 택해야 하지 않을까

### 디렉토리 생성해 데이터 추출

- 데이터 확보건

In [ ]:
#### 아직 미진행....
#### 여기서 텍스트, 이미지, figure 추출하고 저장
#### 아래는 프롬프트로 LLM 통해 텍스트화 (프롬프트 고도화도 포함)
#### 벡터 DB 저장
#### 벡터 DB 저장 내용 가져와 사용 방안
#### 각 유형 따라 결과 도출

- Test 위한 데이터 확보건

In [ ]:
#### 위 df 확보시 Q&A, GT 생성
#### Test (RAGAS / LLM as a Judge / langchain evaluate)

- 추가 실험 건

In [ ]:
#### LLM >>> sLM
#### 오픈소스, 비용 낮춰도 가능하게
#### 프롬프틑 고도화

### Test 전 Demo

**기존 쿼리 기반 추출 코드(Basic) - Metadata**

In [ ]:
"""
import os
import pandas as pd
from langchain.document_loaders import ArxivLoader
from pdf2image import convert_from_path
from huggingface_hub import hf_hub_download
import cv2
from doclayout_yolo import YOLOv10
from PIL import Image

# ArxivLoader를 활용해 논문을 가져옵니다
loader = ArxivLoader(
    query="Agent",
    load_max_docs=20,              # 최대 문서 수
    load_all_available_meta=True   # 메타데이터 전체 로드 여부
)
docs = loader.load()

# 메타데이터 정보를 데이터프레임으로 저장
metadata_list = []
for doc in docs:
    metadata = doc.metadata
    metadata_list.append({
        'Title': metadata.get('Title', ''),
        'Summary': metadata.get('Summary', ''),
        'PDF Link': metadata.get('links', [])[-1] if metadata.get('links') else ''
    })

dataframe = pd.DataFrame(metadata_list)

# 데이터프레임 확인
print(dataframe)

# DocLayout-YOLO 및 필수 패키지 설치
os.system("pip install git+https://github.com/opendatalab/DocLayout-YOLO.git")
os.system("pip install pdf2image huggingface_hub")
os.system("sudo apt-get install poppler-utils")

# PDF 다운로드 함수
def download_pdf(pdf_url, filename):
    import requests
    response = requests.get(pdf_url)
    with open(filename, 'wb') as f:
        f.write(response.content)
    print(f"Downloaded: {filename}")

# PDF를 이미지로 변환
def convert_pdf_to_images(pdf_path, output_dir):
    try:
        os.makedirs(output_dir, exist_ok=True)
        images = convert_from_path(pdf_path)
        image_paths = []
        for i, image in enumerate(images):
            image_path = os.path.join(output_dir, f"page_{i+1}.jpg")
            image.save(image_path, "JPEG")
            image_paths.append(image_path)
        print(f"Converted {pdf_path} to images in {output_dir}")
        return image_paths
    except Exception as e:
        print(f"Error converting {pdf_path} to images: {e}")
        return []

# DocLayout-YOLO를 활용한 디텍션 및 저장

def extract_content_with_doclayout_yolo(image_paths, output_dir, pdf_index):
    os.makedirs(output_dir, exist_ok=True)

    # Pre-trained 모델 다운로드 및 로드
    model_path = hf_hub_download(repo_id="juliozhao/DocLayout-YOLO-DocStructBench", filename="doclayout_yolo_docstructbench_imgsz1024.pt")
    model = YOLOv10(model_path)

    metadata = []

    for page_number, image_path in enumerate(image_paths, start=1):
        # 모델 예측
        det_res = model.predict(
            source=image_path,   # 이미지 경로
            imgsz=1024,          # 예측 이미지 크기
            conf=0.2,            # 신뢰도 임계값
            device="cpu"         # CPU에서 실행
        )

        # 결과 필터링 및 저장
        for det in det_res[0].boxes:
            bbox = det.xyxy.numpy().flatten()  # 바운딩 박스 좌표 추출
            cls = int(det.cls.cpu().numpy())  # 클래스 인덱스 추출
            label = model.names[cls]

            if label in ["table","table_caption","table_footnote", "figure", "figure_caption","isolate_formula","formula_caption"]:
                image = Image.open(image_path)
                cropped = image.crop((bbox[0], bbox[1], bbox[2], bbox[3]))

                output_label_dir = os.path.join(output_dir, label + "s")
                os.makedirs(output_label_dir, exist_ok=True)
                output_image_path = os.path.join(output_label_dir, os.path.basename(image_path).replace(".jpg", f"_{label}.jpg"))
                cropped.save(output_image_path)
                print(f"Saved {label} to {output_image_path}")

                metadata.append({
                    "pdf_index": pdf_index,
                    "page_number": page_number,
                    "label": label,
                    "bbox": bbox.tolist(),
                    "output_path": output_image_path
                })

    return metadata

# PDF 다운로드 및 콘텐츠 추출 함수
def save_pdfs_and_extract_content(dataframe):
    extracted_data_dir = "extracted_data"
    os.makedirs(extracted_data_dir, exist_ok=True)

    all_metadata = []

    for index, row in dataframe.iterrows():
        pdf_link = row['PDF Link']
        title = row['Title']
        if pdf_link:
            pdf_filename = os.path.join(extracted_data_dir, f"paper_{index+1}.pdf")
            download_pdf(pdf_link, pdf_filename)

            # PDF를 이미지로 변환
            image_output_dir = os.path.join(extracted_data_dir, f"paper_{index+1}_images")
            image_paths = convert_pdf_to_images(pdf_filename, image_output_dir)

            if image_paths:
                # DocLayout-YOLO 디텍션 및 결과 저장
                content_output_dir = os.path.join(extracted_data_dir, f"paper_{index+1}_content")
                metadata = extract_content_with_doclayout_yolo(image_paths, content_output_dir, pdf_index=index+1)
                all_metadata.extend(metadata)
                print(f"Extracted content from {pdf_filename} saved to {content_output_dir}")

    # 메타데이터를 CSV로 저장
    metadata_df = pd.DataFrame(all_metadata)
    metadata_df.to_csv(os.path.join(extracted_data_dir, "detection_metadata.csv"), index=False)
    print(f"Detection metadata saved to {os.path.join(extracted_data_dir, 'detection_metadata.csv')}.")

# 함수 실행
save_pdfs_and_extract_content(dataframe)
"""